export const GET_POKEMONS = 'GET_POKEMONS';
export const GET_POKEMONS_BY_QUERY = 'GET_POKEMONS_BY_QUERY';
export const SORT_BY_NAME = 'SORT_BY_NAME';
export const GET_TYPES = 'GET_TYPES';
export const SORT_BY_ATTACK = 'SORT_BY_ATTACK';
export const DELETE_QUERY = 'DELETE_QUERY'
export const GET_POKEMONS_BY_ID= 'GET_POKEMONS_BY_ID'
export const CREATE_POKEMON = 'CREATE_POKEMON'
export const SORT_BY_STORAGE = 'SORT_BY_STORAGE'
export const DELETE_SORT_BY_STORAGE = 'DELETE_SORT_BY_STORAGE'
export const SORT_BY_TYPE = 'SORT_BY_TYPE'
export const DELETE_SORT_BY_TYPE = 'DELETE_SORT_BY_TYPE'



